### ISSUE TITLE
打开一个websocket却显示多个加入

### ISSUE THREAD

**Issue by lynnchae** [waylau/netty-4-user-guide#11]
[SERVER] - /0:0:0:0:0:0:0:1:55327 离开
[SERVER] - /0:0:0:0:0:0:0:1:55330 加入
[SERVER] - /0:0:0:0:0:0:0:1:55328 离开
[SERVER] - /0:0:0:0:0:0:0:1:55331 加入

打开一个聊天窗口，再打开一个，在前面一个窗口怎么提示有两个加入呢？

**Comment by lynnchae** [comment]
跟HttpRequestHandler这个类的加入有关系

**Comment by waylau** [comment]
@lynnchae 

这边测试没有啥问题呢。应该是后期已经解决了。你再试下
