### ISSUE TITLE
一个拼写错误

### ISSUE THREAD

**Issue by linnanc** [waylau/netty-4-user-guide#14]
在https://waylau.gitbooks.io/netty-4-user-guide/content/Getting-Started/Writing-a-Discard-Server.html 有一个拼写错误
> 2.这里我们覆盖了 chanelRead() 事件处理方法。每当从客户端收到新的数据时，这个方法会在收到消息时被调用，这个例子中，收到的消息的类型是 ByteBuf

应为channelRead

**Comment by waylau** [comment]
@bujianzhiyuan  已经修复，感谢反馈！！
