### ISSUE TITLE
文章中的图片似乎都挂了

### ISSUE THREAD

**Issue by wao3** [waylau/netty-4-user-guide#16]
如题，看了 md 文件，好像是图床的问题，比如`http://99btgc01.info/uploads/2015/02/buf01.png`是访问不了的

**Comment by waylau** [comment]
@wao3  感谢反馈，已经修正

**Comment by nadirvishun** [comment]
@waylau 当前时间还是不显示图片的。

**Comment by waylau** [comment]
@nadirvishun  网络问题，github上的图片渲染的比较慢，有时候会渲染失败。

可以从这个入口访问：  https://waylau.com/netty-4-user-guide/
