### ISSUE TITLE
最后一章，其他的页面打不开

### ISSUE THREAD

**Issue by BigBroB** [waylau/netty-4-user-guide#6]
最后一章，其他的页面打不开，还有就是获取部分无法阅读图片的地址，在浏览器打开后是H网站

**Comment by waylau** [comment]
@BigBroB   最后一章，是只  https://waylau.com/netty-time-out-and-heartbeat/  链接到我博客里面的文章打不开码》？？多刷新几次就好了。或者翻墙。


部分，图片之前是放在第三方的服务器上，现在那些服务器貌似停止服务了。这个我后期修复下~
