### ISSUE TITLE
netty 4.x用户指南中文版图丢失

### ISSUE THREAD

**Issue by seedskys** [waylau/netty-4-user-guide#7]
例如：
https://waylau.gitbooks.io/netty-4-user-guide/Architectural%20Overview/Architectural%20Overview.html
未找到对应图片，相同的问题还有其他好几处。

**Comment by waylau** [comment]
感谢您反馈！马上处理~

**Comment by waylau** [comment]
@SeedZheng  已经修复。~感谢反馈~
