### ISSUE TITLE
netty的工作流程

### ISSUE THREAD

**Issue by okguo** [waylau/netty-4-user-guide#8]
首先非常感谢你很详细的翻译此篇关于netty的文章。你写的算是已经很详细了，我也读了好多遍了，可是好像还是不太能描述上来netty的工作流程什么的。能否用一张模型图来描述netty的工作流程？

**Comment by waylau** [comment]
@okguo  你好，可以看下这本，https://github.com/waylau/essential-netty-in-action

讲得更加深入一点
